# Generated by Django 4.1.2 on 2022-10-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summery',
            field=models.TextField(blank=True),
        ),
    ]
